### ISSUE TITLE
Add warnings for HashAlgorithm and SignatureAlgorithm registry

### ISSUE THREAD

**Issue by seanturner** [tlswg/draft-ietf-tls-iana-registry-updates#37]
MT suggested that we add the same warnings we have for cipher suites and named groups to all crypto-related registries.  The two remaining crypt-related registries are HashAlgorithm and SignatureAlgorithm and both are being orphaned.  Despite the fact they are being orphaned we should still add similar text.

@jsalowey Are there any others that should include the warning?

**Comment by jsalowey** [comment]
merged
