### ISSUE TITLE
We should probably say that experimental/private use really means private

### ISSUE THREAD

**Issue by ekr** [tlswg/draft-ietf-tls-iana-registry-updates#56]
I.e., if you actually deploy on the Internet with these experimental code points, and you run into someone using the same code point, you're going to have a bad day. For widespread experiments, we should really be using temporary reservations of some kind instead.

**Comment by seanturner** [comment]
@ekr @jsalowey: How about we add the following note everywhere we added private use:

NOTE:
: As specified in {{RFC5226}}, assignments made in the Private Use space "are not generally useful for broad interoperability."  It is the responsibility of those making use of the Private Use range to ensure that no conflicts occur (within the intended scope of use).  For widespread experiments, temporary reservations are available.

**Comment by ekr** [comment]
LGTM.

**Comment by seanturner** [comment]
Addressed by #57.
